# docker-compose.yml
version: '3.9'

services:
  # node-red:
  #   image: nodered/node-red:latest
  #   environment:
  #     - TZ=Europe/Rome
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - ./node-red-data:/data

  spark-master:
    build: ./spark
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MODE=master
  spark-worker:
    build: ./spark
    volumes:
      - ./spark-data:/data
    deploy:
      replicas: 1

    ports:
      - '8081:8081'
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2

  # spark:
  #   image: bitnami/spark:latest
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   volumes:
  #     - ./spark-data:/data
  #   ports:
  #     - '8080:8080'
  #     - '7077:7077'
  #     - '4040:4040'

  # spark-worker:
  #   image: bitnami/spark:latest
  #   volumes:
  #     - ./spark-data:/data
  #   deploy:
  #     replicas: 2
  #   depends_on:
  #     - spark
    
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no