# docker-compose.yml
version: '3.9'

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Rome
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data

  spark-master:
    build: ./spark/cluster
    volumes:
      - ./spark-data:/data
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MODE=master
  spark-worker:
    build: ./spark/cluster
    volumes:
      - ./spark-data:/data
    deploy:
      replicas: 1

    ports:
      - '8081:8081'
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
  spark-driver:
    build: ./spark/driver
    volumes:
      - ./spark-data:/data
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-driver
    depends_on:
      - spark-master

  # mpi:
  #   build: ./mpi
  #   deploy:
  #     replicas: 2