[kafka]
broker = "kafka:9092" # Endpoint of the kafka broker
topic = "poi-data" # Topic for the simulated data

[simulation]
# Bounds of the region
lat_0 = 45.0
lon_0 = 9.0
lat_1 = 45.01
lon_1 = 9.01
# Time between each discretized simulation step
time_step = 3

### Entities
[simulation.vehichles]
number = 250
noise = 90.0    # dBm
velocity = 20.0 # m/s

[simulation.people]
number = 1500
noise = 40.0    # dBm
velocity = 3.0  # m/s
###

### Sensors
[[simulation.sensor]]
id = "sim-000"
lat = 45.002363
lon = 9.0045677

[[simulation.sensor]]
id = "sim-001"
lat = 45.002564
lon = 9.0099475

[[simulation.sensor]]
id = "sim-002"
lat = 45.0023456
lon = 9.00974535

[[simulation.sensor]]
id = "sim-003"
lat = 45.0045677
lon = 9.0025677

[[simulation.sensor]]
id = "sim-004"
lat = 45.000363
lon = 9.00785677
###